common:
    method: ours 

    net:
        type: SNAKE
        kwargs:
            c_dim: 32
            input_type: pointcloud
            sigmoid: True

            encoder: pointnet_local_pool
            encoder_kwargs:
                hidden_dim: 32
                plane_type: 'grid'
                grid_resolution: [100, 100, 100]
                unet3d: True
                unet3d_kwargs:
                    num_levels: 4
                    f_maps: 32
                    in_channels: 32
                    out_channels: 32
            
            decoder:
                decoder_occup: 
                    decoder_type: simple_local
                    decoder_kwargs:
                        sample_mode: bilinear # bilinear / nearest
                        hidden_size: 32
                
                decoder_keypoint: 
                    decoder_type: simple_local
                    decoder_kwargs:
                        sample_mode: bilinear # bilinear / nearest
                        hidden_size: 32
                        # shared_layers: 0 # occupancy and keypoint shared layers

    solver:
        type: Solver
    
    loss:
        loss1:
            type: Occupancy_loss
            kwargs:
                weight: 1.0
        
        loss2:
            type: CosimLoss
            kwargs:
                weight: 1.0
        
        loss3:
            type: Sparsity_Loss
            kwargs:
                weight: 1.0
                occp_thr: 0.5
                occp_point_ratio: 0.05
        
        loss4:
            type: Surface_Loss
            kwargs:
                weight: 1.0
    
    public_params:
        input_pcd_num: 10240
        on_occupancy_num: 3000 # 1000
        off_occupancy_num: 3000 # 1000
        padding: 0.125
        grid_reso: 8
        x_res_grid: [-0.5, 0.5, 10]
        y_res_grid: [-0.5, 0.5, 10]
        z_res_grid: [-0.5, 0.5, 10]
        total_grid_num: 150
        z_min: -0.5
        z_max: 0.5
    
    optim:
        type: Adam
        kwargs:
            weight_decay: 0.0005
            #momentum: 0.9
            #nesterov: True
    
    lr_scheduler:
        type: Step
        kwargs:
            lr_step_size: [15]
            lr_mults: 0.1
            base_lr: 0.0001

    workers: 8
    batch_size: 6

    max_epoch: 20
    print_freq: 100
    val_freq: 3000
    save_interval: 5000
    save_epoch_interval: 4
    deterministic: True
    random_seed: 134

augmentation:
    do_aug: True
    rotate_angle: 360
    rotate_dim: 3D
    sigma: 0.005
    clip: 0.01
    translation_perturbation: True
    shift_x: [-0.3, 0.3]
    shift_y: [-0.3, 0.3]
    shift_z: [-0.3, 0.3]
    mean_pcd: True
    max_down_sample: 4
    

data_info:
    dataset_name: match3d
    data_path: data/3DMatch_npy/
    train_file: core/datasets/split/match3d_train_new_40k.txt
    val_file: core/datasets/split/match3d_val.txt

evaluate:
    